### ISSUE TITLE
SSDP messages missing "SERVER" field

### ISSUE THREAD

**Issue by matt-hammond-001** [fraunhoferfokus/peer-ssdp#5]
The UPnP Device Architecture v1.x requires that messages sent by the server include a "SERVER" field. This is missing.

The field needs to be a string containing space-separated "product tokens" of the form "NAME/VERSION". The first three tokens need to be: about the OS, UPnP stack and product. e.g. “SERVER: unix/5.1 UPnP/1.1 MyProduct/1.0”

See http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf page 23

**Comment by matt-hammond-bbc** [comment]
Specifically this is on the "200 OK" UDP responses. Other messages, such as NOTIFY seem to include it.

**Comment by matt-hammond-bbc** [comment]
Have just discovered this is a bug in https://github.com/fraunhoferfokus/peer-dial ... not a bug in this repository.

Will raise the issue there instead as https://github.com/fraunhoferfokus/peer-dial/issues/3
